# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#source 'https://github.com/ABTSoftware/PodSpecs.git'
target 'HLX Trader' do
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'RLBAlertsPickers', :git => 'https://github.com/jbouaziz/Alerts-Pickers.git', :branch => 'master'
  
  pod 'M13Checkbox', :git => 'https://github.com/Marxon13/M13Checkbox.git', :branch => 'master'#:tag => '3.4.1'
  pod 'Starscream'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['LD_NO_PIE'] = 'NO'
        end
    end
end
